// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codeFirst.Models;

namespace codeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("codeFirst.Models.Lop", b =>
                {
                    b.Property<int>("IdLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameLop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLop");

                    b.ToTable("Lop");

                    b.HasData(
                        new
                        {
                            IdLop = 1,
                            NameLop = "16T3"
                        });
                });

            modelBuilder.Entity("codeFirst.Models.SinhVien", b =>
                {
                    b.Property<string>("Mssv")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<string>("NameSv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mssv");

                    b.HasIndex("IdLop");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            Mssv = "102160135",
                            Age = 22,
                            IdLop = 1,
                            NameSv = "Duy"
                        });
                });

            modelBuilder.Entity("codeFirst.Models.SinhVien", b =>
                {
                    b.HasOne("codeFirst.Models.Lop", "lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
